### PR TITLE
Refactor code

### PR DESCRIPTION
**Pull request by HenriDellal**
Needs review and testing

### CODE REVIEW

**Comment by g7** [comment]
I have yet to test this, but generally looks ok to me. Does it work on your device?

Plus, this is my personal opinion - and you should wait for feedback from @erikinkinen - but backslashes are very un-pythonic and should not be abused. Please use implied line continuation when possible. Python's own [PEP8](https://www.python.org/dev/peps/pep-0008/#id19) style guide might be a good inspiration.

I would also like for commits to be more descriptive, "Refactoring" is not really useful when looking through the repository history. "Styling and line-length changes" looks better for this specific case, in my opinion.

Thanks.

**Comment by HenriDellal** [comment]
> I have yet to test this, but generally looks ok to me. Does it work on your device?

I don't have any device to test this on.

>  Plus, this is my personal opinion - and you should wait for feedback from @erikinkinen - but backslashes are very un-pythonic and should not be abused. Please use implied line continuation when possible. 

I'll make changes as requested.

> I would also like for commits to be more descriptive

Will do that as well.

**Comment by erikinkinen** [comment]
Looks good to me. I think this could be merged after squashing the refactoring commits.

**Comment by erikinkinen** [comment]
Closing as there is no activity.

**Pull request closed without merging**
