### PR TITLE
Allow using with ofono phonesim

### PR DESCRIPTION
**Pull request by jbruechert**
This makes it possible to use ofono-phonesim for testing ModemManager applications

### CODE REVIEW

**Review by erikinkinen — APPROVED** [review]
LGTM

**Comment by FakeShell** [comment]
i think instead of just allowing certain modems it would be best to try make it work with all modems
testing with a quectel modem i also had to add something here but not ideal really

**Comment by jbruechert** [comment]
What was the intention behind this check initially?

**Comment by FakeShell** [comment]
it was added here https://github.com/droidian/oFono2MM/commit/46cc92a6b41a7f33dc352b679d2120c1ae37b384
maybe @g7 can give us some insights

**Comment by erikinkinen** [comment]
> it was added here [46cc92a](https://github.com/droidian/oFono2MM/commit/46cc92a6b41a7f33dc352b679d2120c1ae37b384) maybe @g7 can give us some insights

The reason it was added initially was that oFono exported some non-existent modems on the bus for a short time and oFono would not respond to any queries on those modem which would hang oFono2MM. The fun part is that it only seems to occur on some devices. I have none such devices, but it did occur on some of Eugenio's devices iirc.

**Comment by erikinkinen** [comment]
And I agree that it would be better to actually fix the root cause of the problem and allow any modems to be used with oFono2MM.

**Comment by g7** [comment]
yes, 100% agreed on what @erikinkinen said. This needs to be properly fixed, but in the mean time it is more than acceptable imho to merge this.

**Pull request merged**
